### ISSUE TITLE
Add a JS program showing callbacks (anonymous functions)

### ISSUE THREAD

**Issue by kshitij86** [kshitij86/hacktoberfest2020-js#10]

**Comment by ishan-chaudhary** [comment]
Hey, Please assign this issue to me .

**Comment by kshitij86** [comment]
Your contribution is welcome @ishan-chaudhary
This has been assigned to you. Feel free to ask if you have any questions!

**Comment by ishan-chaudhary** [comment]
Please accept my pull request
