### ISSUE TITLE
 Add a JS program showing JS closures

### ISSUE THREAD

**Issue by kshitij86** [kshitij86/hacktoberfest2020-js#14]

**Comment by iamvaishnav** [comment]
I'd like to work on this issue

**Comment by or-yam** [comment]
i can do it. 
create new file in src/examples  ?

**Comment by kshitij86** [comment]
Your contribution is welcome @or-yam 
This has been assigned to you. 
All code files belong in the `src` directory. Feel free to ask if you have any further questions!
