### ISSUE TITLE
 Add a JS program showing currying in JS (evaluating a function with multiple arguments, in a sequence)

### ISSUE THREAD

**Issue by kshitij86** [kshitij86/hacktoberfest2020-js#15]

**Comment by computnik** [comment]
Hi @kshitij86 
I would love to pick this one, if its okay with you?

**Comment by kshitij86** [comment]
Your contribution is welcome @computnik 
This has been assigned to you. Feel free to ask if you have any questions!

**Comment by computnik** [comment]
@kshitij86 I have sent a PR #20 to address this. Please review !
