### ISSUE TITLE
Add a JS program showing a simple console log.

### ISSUE THREAD

**Issue by kshitij86** [kshitij86/hacktoberfest2020-js#2]

**Comment by Pratikzzz** [comment]
Hey buddy,
I believe you just wanted a js file for showing a message in console right? or I'm getting it completely wrong?

**Comment by Ayush-Khandelwal-007** [comment]
assign it to me :-)

**Comment by kshitij86** [comment]
Your contribution is welcome @Ayush-Khandelwal-007

This has been assigned to you. Feel free to ask if you have any questions!
