### ISSUE TITLE
Add a JS program showing Promises and resolving Promises.

### ISSUE THREAD

**Issue by kshitij86** [kshitij86/hacktoberfest2020-js#4]

**Comment by sarathm09** [comment]
Hi @kshitij86 
I would like to attempt this.

May I know how complex the example should be?

**Comment by kshitij86** [comment]
@sarathm09 A simple example is fine as long as it works and explains briefly what the code does.

**Comment by sarathm09** [comment]
@kshitij86 Sure, I have raised a [PR](https://github.com/kshitij86/hacktoberfest2020-js/pull/9)
Request you to have a look.
